<?php
/**
 * Created by PhpStorm.
 * User: lucas
 * Date: 22/07/17
 * Time: 11:27
 */

namespace Devguar\OContainer\Frontend\Helpers;


class LayoutHelperMaterial extends LayoutHelper
{
    protected static $classCard = 'card';
    protected static $classCardHeader = 'header';
    protected static $classCardBody = 'body';

    protected static $iconEdit = 'edit';
    protected static $iconDelete = 'delete';
    protected static $iconRead = 'zoom_in';
    protected static $iconEmail = 'email';
    protected static $iconPay = 'check';
    protected static $iconCancel = 'cancel';
    protected static $iconBack = 'arrow_back';

    protected static function makeHeaderCard($title){
        return '<div class="'.static::$classCardHeader.'"><h2>' . $title . '</h2></div>';
    }

    protected static function makeIcon($icon){
        return '<i class="material-icons">'.$icon.'</i>';
    }

    protected static function makeButtonClass($color, $justIcon){
        $class = 'btn btn-'.$color.' waves-effect';

        if ($justIcon){
            $class .= ' btn-circle waves-circle waves-float';
        }

        return $class;
    }

    protected static function makeButtonLabel($label)
    {
        return '<span>'.$label.'</span>'; // TODO: Change the autogenerated stub
    }

    public static function buttonAddBig($url){
        return '<a class="btn btn-primary btn-circle-lg waves-effect waves-circle waves-float" href="'.$url.'"><i class="material-icons">add</i></a>';
    }



}