<?php
/**
 * Created by PhpStorm.
 * User: lucas
 * Date: 22/07/17
 * Time: 11:27
 */

namespace Devguar\OContainer\Frontend\Helpers;


use Illuminate\Support\Facades\App;

class LayoutHelperMaterial extends LayoutHelper
{
    protected static $classCard = 'card';
    protected static $classCardHeader = 'header';
    protected static $classCardBody = 'body';

    protected static $iconEdit = 'edit';
    protected static $iconDelete = 'delete';
    protected static $iconRead = 'zoom_in';
    protected static $iconEmail = 'email';
    protected static $iconPay = 'check';
    protected static $iconCancel = 'cancel';
    protected static $iconBack = 'arrow_back';
    protected static $iconHelp = 'help';

    protected static function makeHeaderCard($title){
        return '<div class="'.static::$classCardHeader.'"><h2>' . $title . '</h2></div>';
    }

    protected static function makeIcon($icon){
        return '<i class="material-icons">'.$icon.'</i>';
    }

    protected static function makeButtonClass($color, $justIcon){
        if(App::environment('testing')){
            return '';
        }

        $class = 'btn btn-'.$color.' waves-effect';

        if ($justIcon){
            $class .= ' btn-circle waves-circle waves-float';
        }

        return $class;
    }

    protected static function makeButtonLabel($label)
    {
        return '<span>'.$label.'</span>'; // TODO: Change the autogenerated stub
    }

    public static function buttonAddBig($url, $config = array())
    {
        if (!isset($config['id'])){
            $config['id'] = "btn_adicionar";
        }

        if(App::environment('testing')){
            return '<a id="'.$config['id'].'" href="'.$url.'">adicionar</a>';
        }

        return '<a class="btn btn-primary btn-circle-lg waves-effect waves-circle waves-float" id="'.$config['id'].'" href="'.$url.'"><i class="material-icons">add</i></a>';
    }



}